services:
  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.94
    container_name: rustfs
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: "true"
    volumes:
      - rustfs_data:/data
    command: /data

  coordinator:
    build:
      context: .
      dockerfile: cmd/coordinator/Dockerfile
    depends_on:
      - rustfs

  worker:
    env_file:
      - .env
    environment:
      COORDINATOR_ADDR: coordinator:50051
      RUSTFS_ENDPOINT_URL: http://rustfs:9000
    build:
      context: .
      dockerfile: cmd/worker/Dockerfile
    depends_on:
      - rustfs
      - coordinator
    deploy:
      replicas: 2
    

volumes:
  rustfs_data:
